# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc82bfb0f02cf07ba31aab364d9a45a24b047c56c3024a60252696ad3d52303d4d7720df9d84aae6724ab14f5f97cedc52a15b50a6f0ed81268c5e6e6ca2cf1

test:
  secret_key_base: 871d07715c2197c65081ac811115f6c5cdd29f1c183e3a3dccb410954577ebba37a3a5dd026a39da692ee8bd050a37832bb443176949b54a49353b0c35e94e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
